### PR TITLE
Controller has too many parameters in the constructor

### PR DESCRIPTION
**Pull request by joewandy**
Fixes for #77 

- Created an [`AdvancedParams`](https://github.com/sdrogers/vimms/blob/iss_77/vimms/Controller/base.py#L8-L41) class to hold all the advanced mass spec params (like AGC, maxit, etc) that are shared by all controller classes.
- We can pass this `AdvancedParams` to the base [`Controller`](https://github.com/sdrogers/vimms/blob/iss_77/vimms/Controller/base.py#L44-L49) class. When this is set to None, an instance of `AdvancedParams` is created with all the default values.
```
class Controller(object):
    def __init__(self, params=None):
        if params is None:
            self.params = AdvancedParams()
        else:
            self.params = params
```
- Made sure that all classes that extend from `Controller` passes this param to the super constructor, instead of having the huge number of parameters in each controller before, e.g. [in TopN](https://github.com/sdrogers/vimms/blob/iss_77/vimms/Controller/topN.py#L17-L19) now it is:
```
class TopNController(Controller):
    def __init__(self, ionisation_mode, N, isolation_width, mz_tol, rt_tol, min_ms1_intensity,
                 ms1_shift=0, initial_exclusion_list=None, params=None):
        super().__init__(params=params)
```
- Finally, added two methods in the base class [`get_ms1_scan_params`](https://github.com/sdrogers/vimms/blob/iss_77/vimms/Controller/base.py#L59-L68) and [`get_ms2_scan_params`](https://github.com/sdrogers/vimms/blob/iss_77/vimms/Controller/base.py#L70-L80) to generate the actual scan params making use of the `self.params` property stored above. (Almost) all controllers were modified to call these two methods when making the MS1 and MS2 scans.

```
                dda_scan_params = self.get_ms2_scan_params(mz, intensity, precursor_scan_id, self.isolation_width,
                                                           self.mz_tol, self.rt_tol)
                new_tasks.append(dda_scan_params)
```
- Would be nice if `get_ms1_scan_params` and `get_ms2_scan_params` don't need to depend on [`get_default_scan_params`](https://github.com/sdrogers/vimms/blob/iss_77/vimms/Environment.py#L182-L206) and [`get_dda_scan_params`](https://github.com/sdrogers/vimms/blob/iss_77/vimms/Environment.py#L208-L266) from the environment. See issue #121.

### CODE REVIEW

**Comment by joewandy** [comment]
One test failed (twice?!) on the server, but it works locally

**Review by sdrogers — APPROVED** [review]
Looks good Joe, thanks.
You say that almost all controllers have been updated -- which oones remain to be done? Should make that an issue if needed?
Not worried about the test. Suspect some difference in the randomness somehow. Be good to update those tests to use the data generation in which we can be sure things will be present...

**Comment by sdrogers** [comment]
happy to merge once confirm which controllers haven't been done.
Also, changes like this should probably motivate us to make slightly more useful test cases --  i.e. our tests check that they run, but if a parameter wasn't being set properly, they wouldn't. Could we add something to the tests that compares the parameters coming back in the scan match those in the `AdvancedParams` class?

**Comment by joewandy** [comment]
> happy to merge once confirm which controllers haven't been done.

There are two: 
- The first is the AIF controller where it's sending an MS1 scan but using ms2 parameters. https://github.com/sdrogers/vimms/blob/iss_77/vimms/Controller/dia.py#L35-L43. It seems that it's easier to just let the controller manually construct the scan params however it wants, rather than trying to make use of such methods from the parent class. 
- The second is the tree controller that vinny is changing now to make it work with the new code structure.

> Also, changes like this should probably motivate us to make slightly more useful test cases -- i.e. our tests check that they run, but if a parameter wasn't being set properly, they wouldn't. Could we add something to the tests that compares the parameters coming back in the scan match those in the `AdvancedParams` class?

Added as a new issue #123

**Comment by sdrogers** [comment]
ok, cool. Merging.

**Pull request merged**
